name: web_example
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc. A Fork of Dio by wendux <824783146@qq.com> originally in https://github.com/flutterchina/web
version: 0.0.1
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  web:
    path: web
  web_http2_adapter:
    path: plugins/http2_adapter
  cookie_manager:
    path: plugins/cookie_manager
  http2: ^2.0.0
  test: ^1.16.2
  test_coverage: ^0.5.0

